/**
* @author Rémi Le Guin
* @date 10/10/2019
* @description Test class for the utility class for the Email Message standard object whithin the Service package.
*/
@IsTest
private class Service_EmailMessageUtilities_Test {

    /**
    * @description Data setup for the Service_EmailMessageUtilities_Test test class.
    */
    @TestSetup
    private static void setup() {}

    /**
    * @description Test the getEmailMessagesByCaseId method.
    */
    @IsTest
    private static void getEmailMessagesByCaseId_Test() {}

}